[package]
name = "graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics-backend-traits = { path = "../graphics-backend-traits" }
graphics-base-traits = { path = "../graphics-base-traits" }
graphics-types = { path = "../graphics-types" }
hiarc = { path = "../hiarc", features = ["derive"] }
image-utils = { path = "../image-utils" }
math = { path = "../math" }
pool = { path = "../pool", features = ["enable_hiarc"] }

anyhow = { version = "1", features = ["backtrace"] }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
