[package]
name = "base-fs"
version = "0.1.0"
edition = "2024"

[features]
bundled_data_dir = ["include_dir"]

[dependencies]
base-io-traits = { path = "../base-io-traits" }
hiarc = { path = "../hiarc", features = ["derive"] }

# v5.0.1+ brings a MPL 2.0 dependency, i don't really like this lib anyway
anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
directories = { version = "=5.0.0" }
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "ddnet", features = [
  "serde",
  "serde_impl",
] }
log = "0.4"
notify = { version = "8", default-features = false, features = [
  "macos_kqueue",
] }
path-clean = "1"
path-slash = "0.2"
tempfile = { version = "3" }
tokio = { version = "1", features = [
  "rt-multi-thread",
  "sync",
  "fs",
  "time",
  "macros",
] }
virtual-fs = { version = "0.701", default-features = false, features = [
  "host-fs",
] }

include_dir = { version = "0.7", optional = true }

[dev-dependencies]
base-io = { path = "../base-io" }
