[package]
name = "sql"
version = "0.1.0"
edition = "2024"

[features]
mysql = ["ddnet-account-sql/mysql", "game-database/mysql", "sqlx/mysql"]
sqlite = ["ddnet-account-sql/sqlite", "game-database/sqlite", "sqlx/sqlite"]

default = ["mysql", "sqlite"]

[dependencies]
game-database = { path = "../game-database", default-features = false }

anyhow = { version = "1", features = ["backtrace"] }
ddnet-account-sql = { version = "0.3", default-features = false }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "chrono"] }
