[package]
name = "hiarc"
version = "0.1.0"
edition = "2024"

[features]
derive = ["hiarc-macro"]

enable_parking_lot = ["parking_lot"]
enable_spin = ["spin"]
enable_hashlink = ["hashlink"]
enable_tokio = ["tokio"]
enable_anyhow = ["anyhow"]
enable_egui = ["egui"]
enable_fixed = ["fixed"]
enable_rayon = ["rayon"]
enable_time = ["time"]
enable_arc_swap = ["arc-swap"]
enable_kira = ["kira"]
enable_mint = ["mint"]
enable_tinyset = ["tinyset"]
enable_url = ["url"]
enable_either = ["either"]
enable_ascii = ["ascii"]
enable_rustc_hash = ["rustc-hash"]
enable_crossbeam = ["crossbeam"]
enable_ash = ["ash"]
enable_chrono = ["chrono"]
enable_winit = ["winit"]
enable_serde_json = ["serde_json"]

[dependencies]
thiserror = "2.0.17"

hiarc-macro = { path = "../hiarc-macro", optional = true }

anyhow = { version = "1.0.100", default-features = false, optional = true }
arc-swap = { version = "1.7.1", default-features = false, optional = true }
ascii = { version = "1.1.0", default-features = false, optional = true }
ash = { version = "0.38.0", default-features = false, optional = true }
chrono = { version = "0.4.42", default-features = false, optional = true }
crossbeam = { version = "0.8.4", default-features = false, optional = true }
egui = { version = "0.33.0", default-features = false, optional = true }
either = { version = "1.15.0", default-features = false, optional = true }
fixed = { version = "1.29.0", default-features = false, optional = true }
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "ddnet", default-features = false, features = [
  "serde",
  "serde_impl",
], optional = true }
kira = { version = "0.9.6", default-features = false, optional = true }
mint = { version = "0.5.9", default-features = false, optional = true }
parking_lot = { version = "0.12.5", default-features = false, optional = true }
rayon = { version = "1.11.0", default-features = false, optional = true }
rustc-hash = { version = "2.1.1", default-features = false, optional = true }
serde_json = { version = "1.0.145", default-features = false, optional = true }
spin = { version = "0.10.0", default-features = false, features = [
  "spin_mutex",
  "rwlock",
], optional = true }
time = { version = "0.3.44", default-features = false, optional = true }
tinyset = { version = "0.5.2", default-features = false, optional = true }
tokio = { version = "1.48.0", default-features = false, features = [
  "sync",
], optional = true }
url = { version = "2.5.7", default-features = false, optional = true }
winit = { version = "0.30.12", default-features = false, optional = true }
