[package]
name = "graphics-types"
version = "0.1.0"
edition = "2024"

[package.metadata.cargo-machete]
ignored = ["num-traits"]

[dependencies]
hiarc = { path = "../hiarc", features = ["enable_hashlink"] }
math = { path = "../math" }
pool = { path = "../pool", features = ["enable_hiarc"] }

bitflags = { version = "2", features = ["serde"] }
num-traits = "0.2"
serde = "1"
strum = { version = "0.27", features = ["derive"] }
