[package]
name = "graphics-backend-traits"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics-base-traits = { path = "../graphics-base-traits" }
graphics-types = { path = "../graphics-types" }
hiarc = { path = "../hiarc", features = ["derive"] }
pool = { path = "../pool" }

anyhow = { version = "1", features = ["backtrace"] }
bitflags = { version = "2", features = ["serde"] }
thiserror = "2"
