[package]
name = "ui-generic"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics = { path = "../graphics" }
math = { path = "../math" }
ui-base = { path = "../ui-base" }

egui = { version = "0.34", default-features = false, features = ["serde"] }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
