[package]
name = "bin-patch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
zstd = { version = "0.13", default-features = false, features = [
  "experimental",
  "zdict_builder",
] }

[dev-dependencies]
base = { path = "../base" }
bidiff = "1"
brotli = "8"
bsdiff = "0.2"
qbsdiff = "1"
