[package]
name = "dilate"
version = "0.1.0"
edition = "2024"

[dependencies]
image-utils = { path = "../../lib/image-utils" }

clap = { version = "4", features = ["derive"] }
oxipng = { version = "9.1", features = ["parallel"], default-features = false }
rayon = "1"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "sync",
  "fs",
  "time",
  "macros",
] }
