[package]
name = "game-state-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
api-wasm-macros = { path = "../../lib/api-wasm-macros" }
base = { path = "../../lib/base" }
base-io = { path = "../../lib/base-io" }
base-io-traits = { path = "../../lib/base-io-traits" }
cache = { path = "../../lib/cache" }
game-database = { path = "../../lib/game-database" }
math = { path = "../../lib/math" }
pool = { path = "../../lib/pool" }
wasm-logic-db = { path = "../../lib/wasm-logic-db" }
wasm-runtime = { path = "../../lib/wasm-runtime" }

game-interface = { path = "../game-interface" }
vanilla = { path = "../vanilla" }

#ddnet = { git = "https://gitlab.com/Jupstar/twgame", rev = "4e5bd44981a2b27d9b46d0db0442f84e81c90cb8" }
anyhow = { version = "1", features = ["backtrace"] }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
wasmer = { version = "6", default-features = false, features = [
  "sys",
  "cranelift",
] }
