[package]
name = "wasm-logic-sound"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../base" }
hiarc = { path = "../hiarc", features = [
  "derive",
  "enable_hashlink",
  "enable_rustc_hash",
] }
sound = { path = "../sound" }
wasm-runtime-types = { path = "../wasm-runtime-types" }

anyhow = { version = "1", features = ["backtrace"] }
sendable = "0.6"
wasmer = { version = "7", default-features = false, features = [
  "sys",
  "cranelift",
] }
