[package]
name = "editor-lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
editor = { path = "../../../game/editor" }

base-io = { path = "../../../lib/base-io" }
config = { path = "../../../lib/config" }
graphics = { path = "../../../lib/graphics" }
sound = { path = "../../../lib/sound" }

egui = { version = "0.33", default-features = false, features = ["serde"] }
once_cell = "1"
rayon = "1"
