[package]
name = "map"
version = "0.1.0"
edition = "2024"

[features]
rust_zstd = [
  "dep:ruzstd",
] # enables a pure rust zstd decoder, which is much slower, but allows tests with miri

[dependencies]
assets-base = { path = "../assets-base" }

base = { path = "../../lib/base" }
hiarc = { path = "../../lib/hiarc", features = [
  "enable_time",
  "enable_hashlink",
  "enable_rustc_hash",
] }
image-utils = { path = "../../lib/image-utils" }
math = { path = "../../lib/math" }

anyhow = { version = "1.0.100", features = ["backtrace"] }
bincode = { features = ["serde"], version = "2.0.1" }
bitflags = { version = "2.10.0", features = ["serde"] }
fixed = "1.29.0"
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "ddnet", features = [
  "serde",
  "serde_impl",
] }
is_sorted = "0.1.1"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_with = "3.15.1"
time = { version = "0.3.44", features = ["serde"] }
tracing = { version = "0.1.41", default-features = false, features = [
  "attributes",
] }
zstd = { version = "0.13", default-features = false, features = [
  "experimental",
  "zdict_builder",
] }

ruzstd = { version = "0.8.2", optional = true }

[dev-dependencies]
base-fs = { path = "../../lib/base-fs" }
base-io = { path = "../../lib/base-io" }
bitcode = { version = "0.6.9", default-features = false, features = [
  "serde",
  "std",
] }
brotli = "8.0.2"
difference = "2.0"
#rust-lzma = "0.6.0"
flate2 = "1.1.5"
lz4_flex = { version = "0.11" }
