[package]
name = "console"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
api = { path = "../../../lib/api" }
api-ui = { path = "../../../lib/api-ui" }
graphics = { path = "../../../lib/graphics" }
ui-base = { path = "../../../lib/ui-base" }
ui-generic = { path = "../../../lib/ui-generic" }

api-ui-game = { path = "../../../game/api-ui-game" }
client-containers = { path = "../../../game/client-containers" }
client-render-base = { path = "../../../game/client-render-base" }
client-types = { path = "../../../game/client-types" }
client-ui = { path = "../../../game/client-ui" }

egui = { version = "0.33", default-features = false, features = ["serde"] }
