[package]
name = "editor-server"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../../lib/base" }
base-fs = { path = "../../lib/base-fs" }
base-http = { path = "../../lib/base-http" }
base-io = { path = "../../lib/base-io" }
config = { path = "../../lib/config" }
graphics = { path = "../../lib/graphics" }
graphics-backend = { path = "../../lib/graphics-backend" }
graphics-base-traits = { path = "../../lib/graphics-base-traits" }
graphics-types = { path = "../../lib/graphics-types" }
network = { path = "../../lib/network" }
sound = { path = "../../lib/sound" }
sound-backend = { path = "../../lib/sound-backend" }

editor = { path = "../../game/editor" }

anyhow = { version = "1", features = ["backtrace"] }
chrono = { version = "0.4" }
clap = { version = "4", features = ["derive"] }
ed25519-dalek = { version = "2", features = ["serde"] }
env_logger = "0.11"
log = "0.4"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
x509-cert = { version = "0.2" }
