[package]
name = "editor-server"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../../lib/base" }
base-fs = { path = "../../lib/base-fs" }
base-http = { path = "../../lib/base-http" }
base-io = { path = "../../lib/base-io" }
config = { path = "../../lib/config" }
graphics = { path = "../../lib/graphics" }
graphics-backend = { path = "../../lib/graphics-backend" }
graphics-base-traits = { path = "../../lib/graphics-base-traits" }
graphics-types = { path = "../../lib/graphics-types" }
network = { path = "../../lib/network" }
sound = { path = "../../lib/sound" }
sound-backend = { path = "../../lib/sound-backend" }

editor = { path = "../../game/editor" }

anyhow = { version = "1.0.100", features = ["backtrace"] }
chrono = { version = "0.4.42" }
clap = { version = "4.5.51", features = ["derive"] }
ed25519-dalek = { version = "2.2.0", features = ["serde"] }
env_logger = "0.11.8"
log = "0.4.28"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
x509-cert = { version = "0.2.5" }
