[package]
name = "network"
version = "0.1.0"
edition = "2024"

[features]
enable_brotli = ["brotli"]

[dependencies]
base = { path = "../base" }
pool = { path = "../pool" }

anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
bincode = { features = ["serde"], version = "2" }
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
ed25519-dalek = { version = "2", features = [
  "serde",
  "rand_core",
  "pkcs8",
  "pem",
] }
futures-util = "0.3"
ipnet = "2"
log = "0.4"
pollster = "0.4"
prefix-trie = "0.8"
quinn = { git = "https://github.com/Jupeyy/quinn", rev = "8a5fc90badd30f35025a8beac08037605665ee21", default-features = false, features = [
  "runtime-tokio",
  "rustls",
  "ring",
] }
rand = { version = "0.8", features = ["getrandom"], default-features = false }
rcgen = { version = "0.14" }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spki = { version = "0.7", features = ["fingerprint"] }
thiserror = "2"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "sync",
  "time",
  "macros",
] }
tokio-tungstenite = { version = "0.28", features = [
  "tokio-rustls",
  "rustls-tls-webpki-roots",
] }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
x509-cert = { version = "0.2" }
zstd = { version = "0.13", default-features = false, features = [
  "experimental",
  "zdict_builder",
] }

num-derive = "0.4"
num-traits = "0.2"

brotli = { version = "8", optional = true }
