[package]
name = "community-register-server"
version = "0.1.0"
edition = "2024"

[dependencies]
community = { path = "../../game/community" }

anyhow = { version = "1.0.100", features = ["backtrace"] }
axum = "0.8.6"
clap = { version = "4.5.51", features = ["derive"] }
tokio = { version = "1.48.0", features = [
  "rt-multi-thread",
  "sync",
  "fs",
  "net",
  "time",
  "macros",
] }

tower-http = { version = "0.6.6", features = ["fs", "trace"] }
