[package]
name = "community-register-server"
version = "0.1.0"
edition = "2024"

[dependencies]
community = { path = "../../game/community" }

anyhow = { version = "1", features = ["backtrace"] }
axum = "0.8"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = [
  "rt-multi-thread",
  "sync",
  "fs",
  "net",
  "time",
  "macros",
] }

tower-http = { version = "0.6", features = ["fs", "trace"] }
