[package]
name = "game-database-backend"
version = "0.1.0"
edition = "2024"

[features]
mysql = [
  "ddnet-account-sql/mysql",
  "sql/mysql",
  "game-database/mysql",
  "sqlx/mysql",
]
sqlite = [
  "ddnet-account-sql/sqlite",
  "sql/sqlite",
  "game-database/sqlite",
  "sqlx/sqlite",
]

default = ["mysql", "sqlite"]

[dependencies]
game-database = { path = "../../lib/game-database", default-features = false }
sql = { path = "../../lib/sql", default-features = false }

ddnet-account-sql = { version = "0.3", default-features = false }

# when updating to the next major version check if
# https://github.com/launchbadge/sqlx/issues/3387 is fixed
# and remove the workaround in the code
anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
parking_lot = "0.12"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "chrono"] }

[dev-dependencies]
base = { path = "../../lib/base" }
base-io = { path = "../../lib/base-io" }

tokio = { version = "1", features = [
  "rt-multi-thread",
  "sync",
  "fs",
  "time",
  "macros",
] }
