[package]
name = "client-accounts"
version = "0.1.0"
edition = "2024"

[dependencies]
base-io = { path = "../../lib/base-io" }
steam = { path = "../../lib/steam" }

client-ui = { path = "../client-ui" }
http-accounts = { path = "../http-accounts" }

anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
chrono = { version = "0.4" }
ddnet-account-client-http-fs = { version = "0.4" }
ddnet-accounts-shared = { version = "0.3" }
email_address = { version = "0.2", features = ["serde"] }
serde_json = "1"
url = { version = "2", features = ["serde"] }
