[package]
name = "ingame_menu"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
api = { path = "../../../lib/api" }
api-ui = { path = "../../../lib/api-ui" }
graphics = { path = "../../../lib/graphics" }
math = { path = "../../../lib/math" }
ui-base = { path = "../../../lib/ui-base" }
ui-generic = { path = "../../../lib/ui-generic" }

api-ui-game = { path = "../../../game/api-ui-game" }
client-containers = { path = "../../../game/client-containers" }
client-render-base = { path = "../../../game/client-render-base" }
client-ui = { path = "../../../game/client-ui" }
game-base = { path = "../../../game/game-base" }
game-config = { path = "../../../game/game-config" }
game-interface = { path = "../../../game/game-interface" }

anyhow = { version = "1.0.100", features = ["backtrace"] }
async-trait = "0.1.89"
egui = { version = "0.33.0", default-features = false, features = ["serde"] }
email_address = { version = "0.2.9", features = ["serde"] }
serde_json = "1.0.145"
