[package]
name = "wasm-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-runtime-types = { path = "../wasm-runtime-types" }

anyhow = { version = "1", features = ["backtrace"] }
arrayvec = "0.7"
bincode = { version = "2", features = ["serde"] }
serde = "1"
wasmer = { version = "6", default-features = false, features = [
  "sys",
  "cranelift",
] }
