[package]
name = "steam"
version = "0.1.0"
edition = "2024"

[features]
runtime = ["steamworks"]

[dependencies]
base = { path = "../base" }

steamworks = { version = "0.12", optional = true }

anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
log = "0.4"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "sync",
  "fs",
  "time",
  "macros",
] }
