[package]
name = "wasm-logic-http"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../base" }
base-io = { path = "../base-io" }
base-io-traits = { path = "../base-io-traits" }
wasm-runtime-types = { path = "../wasm-runtime-types" }

bytes = { version = "1", features = ["serde"] }
sendable = "0.6"
url = { version = "2", features = ["serde"] }
wasmer = { version = "6", default-features = false, features = [
  "sys",
  "cranelift",
] }
