[package]
name = "config"
version = "0.1.0"
edition = "2024"

[package.metadata.cargo-machete]
ignored = ["num-traits"]

[dependencies]
command-parser = { path = "../command-parser" }
config-macro = { path = "../config-macro" }
hiarc = { path = "../hiarc", features = ["derive"] }
math = { path = "../math" }

anyhow = { version = "1", features = ["backtrace"] }
atomic_enum = "0.3"
num-derive = "0.4"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
