[package]
name = "legacy-map"
version = "0.1.0"
edition = "2024"

[package.metadata.cargo-machete]
ignored = ["num-traits"]

[dependencies]
base = { path = "../../lib/base" }
config = { path = "../../lib/config" }
graphics-types = { path = "../../lib/graphics-types" }
hiarc = { path = "../../lib/hiarc", features = ["derive"] }
image-utils = { path = "../../lib/image-utils" }
math = { path = "../../lib/math" }

map = { path = "../map" }

anyhow = { version = "1", features = ["backtrace"] }
flate2 = "1"
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "ddnet", features = [
  "serde",
  "serde_impl",
] }
itertools = "0.14"
num-derive = "0.4"
num-traits = "0.2"
rayon = "1"
serde = { version = "1", features = ["derive"] }
time = { version = "0.3", features = ["serde"] }
