[package]
name = "auto-mapper"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
api = { path = "../../../lib/api" }
math = { path = "../../../lib/math" }

api-auto-mapper = { path = "../../../game/api-auto-mapper" }
editor-interface = { path = "../../../game/editor-interface" }

log = "0.4"
rustc-hash = "2"
