[package]
name = "community-server"
version = "0.1.0"
edition = "2024"

[dependencies]
community = { path = "../../game/community" }

base = { path = "../../lib/base" }
game-database = { path = "../../lib/game-database", default-features = false, features = [
  "mysql",
] }
game-database-backend = { path = "../../lib/game-database-backend", default-features = false, features = [
  "mysql",
] }
network = { path = "../../lib/network" }
sql = { path = "../../lib/sql", default-features = false, features = ["mysql"] }

anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
log = "0.4"
reqwest = { version = "0.13", default-features = false, features = ["rustls"] }
serde_json = "1"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "sync",
  "fs",
  "net",
  "time",
  "macros",
] }
url = { version = "2", features = ["serde"] }
x509-cert = { version = "0.2" }

ddnet-account-client-http-fs = { version = "0.4" }
ddnet-account-client-reqwest = "0.4"
ddnet-account-game-server = { version = "0.4" }
ddnet-accounts-shared = { version = "0.3" }
ddnet-accounts-types = { version = "0.2" }
