[package]
name = "state"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[package.metadata.cargo-machete]
ignored = [
  "api",
  "api-macros",
  "api-state",
  "api-wasm-macros",
  "anyhow",
  "arrayvec",
  "async-trait",
  "base",
  "base-io",
  "bincode",
  "bitflags",
  "chrono",
  "command-parser",
  "config",
  "ddnet-accounts-types",
  "flate2",
  "game-base",
  "game-database",
  "game-interface",
  "graphics-types",
  "hashlink",
  "hiarc",
  "legacy-map",
  "log",
  "map",
  "math",
  "num",
  "num-derive",
  "num-traits",
  "pool",
  "rayon",
  "rustc-hash",
  "serde",
  "serde_json",
  "thiserror",
  "vanilla",
]

[dependencies]
api = { path = "../../../lib/api" }
api-macros = { path = "../../../lib/api-macros" }
api-wasm-macros = { path = "../../../lib/api-wasm-macros" }
base = { path = "../../../lib/base" }
base-io = { path = "../../../lib/base-io" }
command-parser = { path = "../../../lib/command-parser" }
config = { path = "../../../lib/config" }
game-database = { path = "../../../lib/game-database" }
graphics-types = { path = "../../../lib/graphics-types" }
hiarc = { path = "../../../lib/hiarc", features = [
  "derive",
  "enable_hashlink",
  "enable_rustc_hash",
] }
math = { path = "../../../lib/math" }
pool = { path = "../../../lib/pool" }

api-state = { path = "../../../game/api-state" }
game-base = { path = "../../../game/game-base" }
game-interface = { path = "../../../game/game-interface" }
legacy-map = { path = "../../../game/legacy-map" }
map = { path = "../../../game/map" }
vanilla = { path = "../../../game/vanilla" }

ddnet-accounts-types = { version = "0.1.0" }

anyhow = { version = "1.0.100", features = ["backtrace"] }
arrayvec = { version = "0.7.6", features = ["serde"] }
async-trait = "0.1.89"
bincode = { features = ["serde"], version = "2.0.1" }
bitflags = { version = "2.10.0", features = ["serde"] }
chrono = { version = "0.4.42", default-features = false, features = ["serde"] }
flate2 = "1.1.5"
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "ddnet", features = [
  "serde",
  "serde_impl",
] }
log = "0.4.28"
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
rayon = "1.11.0"
rustc-hash = "2.1.1"
serde = "1.0.228"
serde_json = "1.0.145"
thiserror = "2.0.17"
tracing = { version = "0.1.41", default-features = false, features = [
  "attributes",
] }
