[package]
name = "sound-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../base" }
config = { path = "../config" }
hiarc = { path = "../hiarc", features = [
  "derive",
  "enable_kira",
  "enable_hashlink",
  "enable_rustc_hash",
  "enable_mint",
] }
math = { path = "../math" }
sound = { path = "../sound" }

anyhow = { version = "1", features = ["backtrace"] }
kira = "0.9"
log = "0.4"
mint = "0.5"
