[package]
name = "game-database"
version = "0.1.0"
edition = "2024"

[features]
mysql = []
sqlite = []

default = ["mysql", "sqlite"]

[dependencies]
game-database-macros = { path = "../game-database-macros" }

hiarc = { path = "../../lib/hiarc", features = ["derive"] }

anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
