[package]
name = "ddnet-info-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../../lib/base" }
base-io = { path = "../../lib/base-io" }
base-io-traits = { path = "../../lib/base-io-traits" }

client-ui = { path = "../client-ui" }

anyhow = { version = "1", features = ["backtrace"] }
axum = "0.8"
reqwest = { version = "0.13", default-features = false, features = [
  "rustls",
  "json",
] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
] }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
url = { version = "2", features = ["serde"] }
log = "0.4"
async-trait = "0.1"
