[package]
name = "graphics-base-traits"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics-types = { path = "../graphics-types" }
hiarc = { path = "../hiarc", features = ["derive"] }
pool = { path = "../pool" }

anyhow = { version = "1", features = ["backtrace"] }
bincode = { features = ["serde"], version = "2" }
serde = { version = "1", features = ["derive"] }
