[package]
name = "client-render-base"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../../lib/base" }
base-io = { path = "../../lib/base-io" }
config = { path = "../../lib/config" }
graphics = { path = "../../lib/graphics" }
graphics-backend-traits = { path = "../../lib/graphics-backend-traits" }
graphics-types = { path = "../../lib/graphics-types" }
hiarc = { path = "../../lib/hiarc", features = ["derive"] }
image-utils = { path = "../../lib/image-utils" }
math = { path = "../../lib/math" }
pool = { path = "../../lib/pool" }
sound = { path = "../../lib/sound" }

assets-base = { path = "../assets-base" }
camera = { path = "../camera" }
client-containers = { path = "../client-containers" }
game-base = { path = "../game-base" }
game-config = { path = "../game-config" }
game-interface = { path = "../game-interface" }
legacy-map = { path = "../legacy-map" }
map = { path = "../map" }
tile-map-collision = { path = "../tile-map-collision" }

hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "ddnet", features = [
  "serde",
  "serde_impl",
] }

anyhow = { version = "1", features = ["backtrace"] }
bincode = { version = "2", features = ["serde"] }
fixed = "1"
futures = "0.3"
log = "0.4"
num-derive = "0.4"
num-traits = "0.2"
rayon = "1"
rustc-hash = "2"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.28", features = ["derive"] }
time = { version = "0.3", features = ["serde"] }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
url = { version = "2", features = ["serde"] }
