[package]
name = "base"
version = "0.1.0"
edition = "2024"

[dependencies]
hiarc = { path = "../hiarc", features = [
  "derive",
  "enable_anyhow",
  "enable_parking_lot",
  "enable_ascii",
] }
pool = { path = "../pool", features = ["hiarc"] }

anyhow = { version = "1", features = ["backtrace"] }
ascii = { version = "1", features = ["serde"] }
blake3 = "1"
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "ddnet", features = [
  "serde",
  "serde_impl",
] }
hex = "0.4"
parking_lot = "0.12"
rayon = "1"
rustc-hash = "2"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
owo-colors = "4"
