[package]
name = "ui-base"
version = "0.1.0"
edition = "2024"

[dependencies]
base-io = { path = "../base-io" }
graphics = { path = "../graphics" }
graphics-types = { path = "../graphics-types" }
hiarc = { path = "../hiarc", features = ["enable_egui"] }
math = { path = "../math" }

anyhow = { version = "1", features = ["backtrace"] }
egui = { version = "0.33", default-features = false, features = ["serde"] }
egui_extras = { version = "0.33" }
serde = { version = "1", features = ["derive"] }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
