[package]
name = "mainmenu"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
api = { path = "../../../lib/api" }
api-ui = { path = "../../../lib/api-ui" }
base-io = { path = "../../../lib/base-io" }
graphics = { path = "../../../lib/graphics" }
ui-base = { path = "../../../lib/ui-base" }
ui-generic = { path = "../../../lib/ui-generic" }

api-ui-game = { path = "../../../game/api-ui-game" }
client-containers = { path = "../../../game/client-containers" }
client-render-base = { path = "../../../game/client-render-base" }
client-ui = { path = "../../../game/client-ui" }
game-base = { path = "../../../game/game-base" }
game-config = { path = "../../../game/game-config" }

anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
egui = { version = "0.33", default-features = false, features = ["serde"] }
email_address = { version = "0.2", features = ["serde"] }
serde_json = "1"
