[package]
name = "native"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../base" }
native-display = { path = "../native-display" }

anyhow = { version = "1", features = ["backtrace"] }
log = "0.4"
raw-window-handle = "0.6"
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
winit = { version = "0.30", features = ["serde", "android-native-activity"] }
