[package]
name = "graphics-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../base" }
base-fs = { path = "../base-fs" }
base-io = { path = "../base-io" }
base-io-traits = { path = "../base-io-traits" }
cache = { path = "../cache" }
config = { path = "../config" }
graphics = { path = "../graphics" }
graphics-backend-traits = { path = "../graphics-backend-traits" }
graphics-base-traits = { path = "../graphics-base-traits" }
graphics-types = { path = "../graphics-types" }
hiarc = { path = "../hiarc", features = [
  "enable_parking_lot",
  "enable_spin",
  "enable_either",
  "enable_crossbeam",
  "enable_hashlink",
  "enable_ash",
  "enable_arc_swap",
  "enable_rustc_hash",
  "enable_rayon",
] }
math = { path = "../math" }
native = { path = "../native" }
pool = { path = "../pool" }

anyhow = { version = "1.0.100", features = ["backtrace"] }
arc-swap = "1.7.1"
ash = "0.38.0"
ash-window = "0.13.0"
atomic_enum = "0.3.0"
bincode = { features = ["serde"], version = "2.0.1" }
crossbeam = "0.8.4"
either = "1.15.0"
futures = "0.3.31"
libc = "0.2.177"
log = "0.4.28"
naga = { version = "27.0.3", features = ["wgsl-in", "spv-out", "glsl-out"] }
naga_oil = "0.20.0"
num-derive = "0.4.2"
num-traits = "0.2.19"
parking_lot = "0.12.5"
raw-window-handle = "0.6.2"
rayon = "1.11.0"
replace_with = "0.1.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"
thread-priority = "3.0.0"

[target.'cfg(target_os = "macos")'.dependencies]
ash-molten = { version = "0.20.0" }

[dev-dependencies]
base-http = { path = "../base-http" }
