[package]
name = "legacy-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../../lib/base" }
base-http = { path = "../../lib/base-http" }
base-io = { path = "../../lib/base-io" }
bin-patch = { path = "../../lib/bin-patch" }
math = { path = "../../lib/math" }
network = { path = "../../lib/network" }
pool = { path = "../../lib/pool" }

game-base = { path = "../game-base" }
game-interface = { path = "../game-interface" }
game-network = { path = "../game-network" }
game-server = { path = "../game-server" }
legacy-map = { path = "../legacy-map" }
map = { path = "../map" }
master-server-types = { path = "../master-server-types" }
vanilla = { path = "../vanilla" }

libtw2-gamenet-ddnet = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0b6b1b7533dc00c48483dca51eedf04656efb66d" }
libtw2-net = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0b6b1b7533dc00c48483dca51eedf04656efb66d" }
libtw2-packer = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0b6b1b7533dc00c48483dca51eedf04656efb66d" }
libtw2-snapshot = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0b6b1b7533dc00c48483dca51eedf04656efb66d" }

anyhow = { version = "1", features = ["backtrace"] }
# stuck for compat with libtw2
arrayvec = "=0.5.2"
# stuck for compat with libtw2
uuid = "=0.8.2"
bincode = { version = "2", features = ["serde"] }
hexdump = "0.1"
rand = { version = "0.10", features = ["thread_rng"] }
sha2 = "0.11"
serde_json = "1"

futures = "0.3"
log = "0.4"
rayon = "1"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "sync",
  "fs",
  "time",
  "macros",
] }
warn = "0.2"
