[package]
name = "wasm-logic-graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics = { path = "../graphics" }
graphics-backend = { path = "../graphics-backend" }
graphics-backend-traits = { path = "../graphics-backend-traits" }
graphics-types = { path = "../graphics-types" }
hiarc = { path = "../hiarc", features = ["derive"] }
wasm-runtime-types = { path = "../wasm-runtime-types" }

sendable = "0.6"
wasmer = { version = "7", default-features = false, features = [
  "sys",
  "cranelift",
] }
