[package]
name = "sound"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../base" }
hiarc = { path = "../hiarc", features = ["derive"] }
math = { path = "../math" }

anyhow = { version = "1", features = ["backtrace"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
