[package]
name = "ui-wasm-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
base-io = { path = "../base-io" }
base-io-traits = { path = "../base-io-traits" }
cache = { path = "../cache" }
config = { path = "../config" }
graphics = { path = "../graphics" }
graphics-backend = { path = "../graphics-backend" }
hiarc = { path = "../hiarc", features = ["derive"] }
sound = { path = "../sound" }
ui-base = { path = "../ui-base" }
ui-generic = { path = "../ui-generic" }
wasm-logic-fs = { path = "../wasm-logic-fs" }
wasm-logic-graphics = { path = "../wasm-logic-graphics" }
wasm-logic-http = { path = "../wasm-logic-http" }
wasm-logic-sound = { path = "../wasm-logic-sound" }
wasm-runtime = { path = "../wasm-runtime" }

anyhow = { version = "1", features = ["backtrace"] }
egui = { version = "0.34", default-features = false, features = ["serde"] }
serde = "1"
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }
wasmer = { version = "7", default-features = false, features = [
  "sys",
  "cranelift",
] }
