[package]
name = "input-binds"
version = "0.1.0"
edition = "2024"

[dependencies]
base = { path = "../base" }
hiarc = { path = "../hiarc", features = ["enable_winit"] }
pool = { path = "../pool" }

serde = { version = "1", features = ["derive"] }
winit = { version = "0.30", features = ["serde", "android-native-activity"] }

[dev-dependencies]
serde_json = "1"
