[package]
name = "pool"
version = "0.1.0"
edition = "2024"

[features]
enable_hiarc = ["hiarc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { version = "2", features = ["serde"] }
hashlink = { git = "https://github.com/Jupeyy/hashlink/", branch = "ddnet", features = [
  "serde",
  "serde_impl",
] }
hiarc = { path = "../hiarc", features = [
  "enable_parking_lot",
  "derive",
], optional = true }
parking_lot = "0.12"
rustc-hash = "2"
serde = { version = "1", features = ["derive", "rc"] }
