[package]
name = "wasm-logic-db"
version = "0.1.0"
edition = "2024"

[dependencies]
base-io = { path = "../base-io" }
game-database = { path = "../game-database" }
wasm-runtime-types = { path = "../wasm-runtime-types" }

sendable = "0.6"
wasmer = { version = "7", default-features = false, features = [
  "sys",
  "cranelift",
] }
